### ISSUE TITLE
CartesianMarker message should contain end-effector/distal-link information?

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/CartesianInterface#1]
Despite this information can be retrieved from the topic name, why don't insert it in the topic message? Or we could provide this information as service? This is of course for the use in non-programmatic way.

**Comment by alaurenzi** [comment]
I have two possibilities:
1) single service with task name as request field
```
string task_name
---
string base_link
string control_mode # pos/vel/disabled
string task_state # reaching/online
bool success # task_name exists
```

2) one service for each task (e.g. `/xbotcore/cartesian/l_sole/get_task_info`) with empy request
```
---
string distal_link
string base_link
string control_mode # pos/vel/disabled
string task_state # reaching/online
bool success # task_name exists
```

**Comment by alaurenzi** [comment]
Second option implemented in latest master
