### ISSUE TITLE
[com] Sending velocity references to the com task does not work

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/CartesianInterface#8]
Despite the topic ```/xbotcore/cartesian/com/velocity_reference``` see the desired references, I think these are not provided internally to the task.
I tried both with the joystick and the topic publisher.

**Comment by alaurenzi** [comment]
Should be fixed in latest devel. Can you give it a try? @EnricoMingo

**Comment by EnricoMingo** [comment]
Tested and working. I'll close.
