### ISSUE TITLE
Wrong Initialization of EigenVector7d

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/CartesianInterface#9]
There are two wrong initialization of couple of EigenVector7d. One is in line 282:

```__otg_maxacc << linear, linear, linear, angular/4.0, angular/4.0, angular/4.0;```

 and one in line 293:

```__otg_maxvel << linear, linear, linear, angular/2.0, angular/2.0, angular/2.0;```

both in ```CartesianInterfaceImpl.cpp```.
These causes error during execution if not compiled in ```RelWithDebInfo```. 
These vectors are initialized with six elements while should be 7 (I suppose last 4 are the quaternion but I am not sure what is the right value for the missing element).

**Comment by alaurenzi** [comment]
Fixed in latest devel e24f31144509953618ba1120b1d
CI running in debug mode && clean valgrind output
